# Generated by Django 3.2.3 on 2021-06-18 06:49

import autoslug.fields
from django.db import migrations
import photodrive.models


class Migration(migrations.Migration):

    dependencies = [
        ('photodrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', slugify=photodrive.models.custom_slugify, unique=True),
        ),
    ]
